CREATE TABLE IF NOT EXISTS public.kiem_kho_can_bang (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phieu_id BIGINT REFERENCES public.kiem_kho(id) ON DELETE CASCADE,
    ma_phieu TEXT NOT NULL,
    stt INT DEFAULT 1,
    ma_vach TEXT NOT NULL,
    ten_hang_hoa TEXT,
    ton_gpet NUMERIC(15,2) DEFAULT 0,
    ton_kho NUMERIC(15,2) DEFAULT 0,
    thuc_te NUMERIC(15,2) DEFAULT 0,
    chenh_lech NUMERIC(15,2) DEFAULT 0,
    trang_thai TEXT,
    ghi_chu TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.kiem_kho_can_bang ADD COLUMN IF NOT EXISTS stt INT DEFAULT 1;
ALTER TABLE public.kiem_kho_can_bang ADD COLUMN IF NOT EXISTS ton_gpet NUMERIC(15,2) DEFAULT 0;
ALTER TABLE public.kiem_kho_can_bang ADD COLUMN IF NOT EXISTS ton_kho NUMERIC(15,2) DEFAULT 0;
ALTER TABLE public.kiem_kho_can_bang ADD COLUMN IF NOT EXISTS thuc_te NUMERIC(15,2) DEFAULT 0;
ALTER TABLE public.kiem_kho_can_bang ADD COLUMN IF NOT EXISTS chenh_lech NUMERIC(15,2) DEFAULT 0;
ALTER TABLE public.kiem_kho_can_bang ADD COLUMN IF NOT EXISTS trang_thai TEXT;
ALTER TABLE public.kiem_kho_can_bang ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_can_bang_phieu_id ON public.kiem_kho_can_bang(phieu_id);
CREATE INDEX IF NOT EXISTS idx_can_bang_ma_phieu ON public.kiem_kho_can_bang(ma_phieu);
CREATE INDEX IF NOT EXISTS idx_can_bang_ma_vach ON public.kiem_kho_can_bang(ma_vach);

ALTER TABLE public.kiem_kho_can_bang ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select on kiem_kho_can_bang" ON public.kiem_kho_can_bang FOR SELECT USING (true);
CREATE POLICY "Allow public insert on kiem_kho_can_bang" ON public.kiem_kho_can_bang FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on kiem_kho_can_bang" ON public.kiem_kho_can_bang FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on kiem_kho_can_bang" ON public.kiem_kho_can_bang FOR DELETE USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.kiem_kho_can_bang;
