-- GAIA Hospital - Bảng Kiểm Kho & Chi Tiết Kiểm Kho (Inventory Audit Tables)

-- 1. Bảng Phiếu Kiểm Kho Tổng (kiem_kho)
CREATE TABLE IF NOT EXISTS public.kiem_kho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_phieu TEXT NOT NULL UNIQUE,
    branch TEXT NOT NULL,
    user_name TEXT,
    tong_ma_quat INT DEFAULT 0,
    tong_so_luong_quat NUMERIC(15,2) DEFAULT 0,
    so_ma_khop INT DEFAULT 0,
    so_ma_du INT DEFAULT 0,
    so_ma_thieu INT DEFAULT 0,
    trang_thai TEXT DEFAULT 'DANG_KIEM',
    ghi_chu TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bổ sung cột nếu bảng đã tồn tại từ trước
ALTER TABLE public.kiem_kho ADD COLUMN IF NOT EXISTS trang_thai TEXT DEFAULT 'DANG_KIEM';
ALTER TABLE public.kiem_kho ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 2. Bảng Chi Tiết Phiếu Kiểm Kho (kiem_kho_chi_tiet)
CREATE TABLE IF NOT EXISTS public.kiem_kho_chi_tiet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phieu_id BIGINT REFERENCES public.kiem_kho(id) ON DELETE CASCADE,
    ma_phieu TEXT NOT NULL,
    ma_qr TEXT,
    ma_vach TEXT,
    ten_hang_hoa TEXT,
    lot TEXT,
    date_expiry DATE,
    so_luong_thuc_te NUMERIC(15,2) DEFAULT 0,
    so_luong_he_thong NUMERIC(15,2) DEFAULT 0,
    chenh_lech NUMERIC(15,2) DEFAULT 0,
    trang_thai TEXT CHECK (trang_thai IN ('KHOP', 'DU', 'THIEU')),
    branch TEXT,
    user_name TEXT,
    thoi_gian_quat TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bổ sung cột nếu bảng chi tiết đã tồn tại từ trước
ALTER TABLE public.kiem_kho_chi_tiet ADD COLUMN IF NOT EXISTS user_name TEXT;
ALTER TABLE public.kiem_kho_chi_tiet ADD COLUMN IF NOT EXISTS thoi_gian_quat TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Indexes tối ưu truy vấn
CREATE INDEX IF NOT EXISTS idx_kiem_kho_branch ON public.kiem_kho(branch);
CREATE INDEX IF NOT EXISTS idx_kiem_kho_created_at ON public.kiem_kho(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_kiem_kho_ct_phieu_id ON public.kiem_kho_chi_tiet(phieu_id);
CREATE INDEX IF NOT EXISTS idx_kiem_kho_ct_ma_qr ON public.kiem_kho_chi_tiet(ma_qr);
CREATE INDEX IF NOT EXISTS idx_kiem_kho_ct_ma_vach ON public.kiem_kho_chi_tiet(ma_vach);

-- Enable RLS
ALTER TABLE public.kiem_kho ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kiem_kho_chi_tiet ENABLE ROW LEVEL SECURITY;

-- RLS Policies cho phép chọn và thêm dữ liệu
CREATE POLICY "Allow public select on kiem_kho" ON public.kiem_kho FOR SELECT USING (true);
CREATE POLICY "Allow public insert on kiem_kho" ON public.kiem_kho FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on kiem_kho" ON public.kiem_kho FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on kiem_kho" ON public.kiem_kho FOR DELETE USING (true);

CREATE POLICY "Allow public select on kiem_kho_chi_tiet" ON public.kiem_kho_chi_tiet FOR SELECT USING (true);
CREATE POLICY "Allow public insert on kiem_kho_chi_tiet" ON public.kiem_kho_chi_tiet FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on kiem_kho_chi_tiet" ON public.kiem_kho_chi_tiet FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on kiem_kho_chi_tiet" ON public.kiem_kho_chi_tiet FOR DELETE USING (true);

-- BẬT SUPABASE REALTIME REPLICATION CHO 2 BẢNG KIỂM KHO (CHẠY TRÊN SUPABASE SQL EDITOR)
ALTER PUBLICATION supabase_realtime ADD TABLE public.kiem_kho;
ALTER PUBLICATION supabase_realtime ADD TABLE public.kiem_kho_chi_tiet;
