CREATE TABLE IF NOT EXISTS public.quet_chi_tiet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phieu_id BIGINT REFERENCES public.kiem_kho(id) ON DELETE CASCADE,
    ma_phieu TEXT NOT NULL,
    ma_vach TEXT NOT NULL,
    ten_hang_hoa TEXT,
    lot TEXT DEFAULT '-',
    date_expiry TEXT,
    so_luong NUMERIC(15,2) DEFAULT 1,
    user_name TEXT NOT NULL,
    branch TEXT NOT NULL,
    client_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.quet_chi_tiet ADD COLUMN IF NOT EXISTS ten_hang_hoa TEXT;
ALTER TABLE public.quet_chi_tiet ADD COLUMN IF NOT EXISTS lot TEXT DEFAULT '-';
ALTER TABLE public.quet_chi_tiet ADD COLUMN IF NOT EXISTS date_expiry TEXT;
ALTER TABLE public.quet_chi_tiet ADD COLUMN IF NOT EXISTS so_luong NUMERIC(15,2) DEFAULT 1;
ALTER TABLE public.quet_chi_tiet ADD COLUMN IF NOT EXISTS client_id TEXT;

DO $$ 
BEGIN 
    ALTER TABLE public.quet_chi_tiet ALTER COLUMN date_expiry TYPE TEXT USING date_expiry::text;
EXCEPTION 
    WHEN OTHERS THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_quet_ct_phieu_id ON public.quet_chi_tiet(phieu_id);
CREATE INDEX IF NOT EXISTS idx_quet_ct_ma_phieu ON public.quet_chi_tiet(ma_phieu);
CREATE INDEX IF NOT EXISTS idx_quet_ct_ma_vach ON public.quet_chi_tiet(ma_vach);
CREATE INDEX IF NOT EXISTS idx_quet_ct_created_at ON public.quet_chi_tiet(created_at DESC);

ALTER TABLE public.quet_chi_tiet ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public select on quet_chi_tiet" ON public.quet_chi_tiet FOR SELECT USING (true);
CREATE POLICY "Allow public insert on quet_chi_tiet" ON public.quet_chi_tiet FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on quet_chi_tiet" ON public.quet_chi_tiet FOR UPDATE USING (true);
CREATE POLICY "Allow public delete on quet_chi_tiet" ON public.quet_chi_tiet FOR DELETE USING (true);

ALTER PUBLICATION supabase_realtime ADD TABLE public.quet_chi_tiet;

CREATE OR REPLACE VIEW public.view_kiem_kho_tong_hop_chi_tiet AS
WITH scan_summary AS (
    SELECT 
        phieu_id,
        ma_phieu,
        ma_vach,
        COALESCE(lot, '-') AS lot,
        MAX(ten_hang_hoa) AS ten_hang_hoa,
        MAX(date_expiry) AS date_expiry,
        SUM(so_luong) AS tong_so_luong_quat,
        MAX(created_at) AS thoi_gian_quat_cuoi,
        jsonb_agg(DISTINCT jsonb_build_object('user_name', user_name, 'branch', branch)) AS scanners_json
    FROM public.quet_chi_tiet
    GROUP BY phieu_id, ma_phieu, ma_vach, COALESCE(lot, '-')
)
SELECT 
    COALESCE(q.phieu_id, c.phieu_id) AS phieu_id,
    COALESCE(q.ma_phieu, c.ma_phieu) AS ma_phieu,
    COALESCE(q.ma_vach, c.ma_vach) AS ma_vach,
    COALESCE(q.ten_hang_hoa, c.ten_hang_hoa) AS ten_hang_hoa,
    COALESCE(q.lot, c.lot, '-') AS lot,
    COALESCE(q.date_expiry, c.date_expiry) AS date_expiry,
    COALESCE(q.tong_so_luong_quat, c.so_luong_thuc_te, 0) AS so_luong_thuc_te,
    COALESCE(c.so_luong_he_thong, 0) AS so_luong_he_thong,
    (COALESCE(q.tong_so_luong_quat, c.so_luong_thuc_te, 0) - COALESCE(c.so_luong_he_thong, 0)) AS chenh_lech,
    CASE 
        WHEN COALESCE(q.tong_so_luong_quat, c.so_luong_thuc_te, 0) = COALESCE(c.so_luong_he_thong, 0) THEN 'KHOP'
        WHEN COALESCE(q.tong_so_luong_quat, c.so_luong_thuc_te, 0) > COALESCE(c.so_luong_he_thong, 0) THEN 'DU'
        ELSE 'THIEU'
    END AS trang_thai,
    COALESCE(q.scanners_json, jsonb_build_array(jsonb_build_object('user_name', c.user_name, 'branch', c.branch))) AS scanners,
    COALESCE(q.thoi_gian_quat_cuoi, c.thoi_gian_quat, c.created_at) AS thoi_gian_quat
FROM scan_summary q
FULL OUTER JOIN public.kiem_kho_chi_tiet c 
    ON (q.phieu_id = c.phieu_id OR q.ma_phieu = c.ma_phieu)
   AND q.ma_vach = c.ma_vach 
   AND q.lot = COALESCE(c.lot, '-');
