CREATE TABLE IF NOT EXISTS public.the_kho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_don TEXT,
    ma_qr TEXT,
    ma_vach TEXT NOT NULL,
    lot TEXT,
    date_expiry DATE,
    ten_hang_hoa TEXT NOT NULL,
    loai TEXT NOT NULL CHECK (loai IN ('Nhập', 'Xuất')),
    so_luong NUMERIC(15, 2) DEFAULT 1,
    muc_dich TEXT,
    user_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.the_kho ADD COLUMN IF NOT EXISTS ma_don TEXT;

CREATE INDEX IF NOT EXISTS idx_the_kho_ma_don ON public.the_kho(ma_don);
CREATE INDEX IF NOT EXISTS idx_the_kho_ma_vach ON public.the_kho(ma_vach);
CREATE INDEX IF NOT EXISTS idx_the_kho_lot ON public.the_kho(lot);
CREATE INDEX IF NOT EXISTS idx_the_kho_loai ON public.the_kho(loai);
CREATE INDEX IF NOT EXISTS idx_the_kho_created_at ON public.the_kho(created_at DESC);

ALTER TABLE public.the_kho DISABLE ROW LEVEL SECURITY;
