-- ==========================================================================
-- GAIA Hospital - Bảng Thẻ Kho (Inventory Movement Log)
-- Chạy script này trên Supabase SQL Editor để khởi tạo bảng 'the_kho'
-- ==========================================================================

-- 1. Tạo Bảng public.the_kho
CREATE TABLE IF NOT EXISTS public.the_kho (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_don TEXT,                               -- Mã Đơn Kho (NK/XK)
    ma_qr TEXT,                                -- Mã QR
    ma_vach TEXT NOT NULL,                     -- Mã Vạch
    lot TEXT,                                  -- Số Lô (LOT)
    date_expiry DATE,                          -- Hạn sử dụng / Ngày lô (Date)
    ten_hang_hoa TEXT NOT NULL,                -- Tên Hàng Hóa
    loai TEXT NOT NULL CHECK (loai IN ('Nhập', 'Xuất')), -- Loại: Nhập hoặc Xuất
    so_luong NUMERIC(15, 2) DEFAULT 1,         -- Số Lượng
    muc_dich TEXT,                             -- Mục Đích / Ghi chú
    user_name TEXT,                            -- Người thực hiện (User)
    created_at TIMESTAMPTZ DEFAULT NOW()       -- Thời gian phát sinh (Time)
);

-- Tự động thêm cột ma_don nếu bảng đã tồn tại từ trước
ALTER TABLE public.the_kho ADD COLUMN IF NOT EXISTS ma_don TEXT;

-- 2. Đặt Index tối ưu tốc độ truy vấn & lọc dữ liệu
CREATE INDEX IF NOT EXISTS idx_the_kho_ma_don ON public.the_kho(ma_don);
CREATE INDEX IF NOT EXISTS idx_the_kho_ma_vach ON public.the_kho(ma_vach);
CREATE INDEX IF NOT EXISTS idx_the_kho_lot ON public.the_kho(lot);
CREATE INDEX IF NOT EXISTS idx_the_kho_loai ON public.the_kho(loai);
CREATE INDEX IF NOT EXISTS idx_the_kho_created_at ON public.the_kho(created_at DESC);

-- 3. Tắt RLS để kết nối ứng dụng mượt mà không bị chặn phân quyền
ALTER TABLE public.the_kho DISABLE ROW LEVEL SECURITY;

-- 4. Chèn dữ liệu mẫu (Sample Data) kiểm thử giao diện
INSERT INTO public.the_kho (ma_qr, ma_vach, lot, date_expiry, ten_hang_hoa, loai, so_luong, muc_dich, user_name, created_at)
VALUES 
('QR-AMOX-500', '8935001234567', 'LOT202601', '2026-12-31', 'Thuốc Kháng Sinh Amoxicillin 500mg', 'Nhập', 100, 'Nhập kho định kỳ từ Mekophar', 'Thái Trung Tín (Quản Lý)', NOW() - INTERVAL '2 days'),
('QR-BIOFEL-PCH', '8935007654321', 'LOT202602', '2027-06-30', 'Vắc xin Phòng 5 Bệnh Cho Mèo (Biofel PCH)', 'Nhập', 50, 'Nhập bổ sung từ Bioveta', 'Thái Trung Tín (Quản Lý)', NOW() - INTERVAL '1 day'),
('QR-AMOX-500', '8935001234567', 'LOT202601', '2026-12-31', 'Thuốc Kháng Sinh Amoxicillin 500mg', 'Xuất', 2, 'Xuất sử dụng ca điều trị #1042', 'Bác sĩ Thú y Hùng', NOW() - INTERVAL '5 hours'),
('QR-BIOFEL-PCH', '8935007654321', 'LOT202602', '2027-06-30', 'Vắc xin Phòng 5 Bệnh Cho Mèo (Biofel PCH)', 'Xuất', 1, 'Xuất tiêm phòng ca #1045', 'Kỹ thuật viên Nam', NOW() - INTERVAL '2 hours');
